export const buildings = [
  { id: "edificio-1", name: "Edificio Las Palmas" },
  { id: "edificio-2", name: "Residencial El Sol" },
  { id: "edificio-3", name: "Torre Vista Mar" },
]

export const departments = [
  {
    id: 1,
    number: "101",
    building: "edificio-1",
    owner: "Carlos Mendoza",
    tenant: "María García",
    debt: 450.0,
    monthsOverdue: 2,
    waterReading: 125,
    electricityReading: 380,
  },
  {
    id: 2,
    number: "102",
    building: "edificio-1",
    owner: "Ana Rodríguez",
    tenant: "Ana Rodríguez",
    debt: 0,
    monthsOverdue: 0,
    waterReading: 98,
    electricityReading: 290,
  },
  {
    id: 3,
    number: "201",
    building: "edificio-1",
    owner: "Luis Pérez",
    tenant: "José Torres",
    debt: 1200.5,
    monthsOverdue: 4,
    waterReading: 156,
    electricityReading: 420,
  },
  {
    id: 4,
    number: "202",
    building: "edificio-1",
    owner: "Rosa Flores",
    tenant: "Rosa Flores",
    debt: 300.0,
    monthsOverdue: 1,
    waterReading: 112,
    electricityReading: 350,
  },
  {
    id: 5,
    number: "301",
    building: "edificio-1",
    owner: "Miguel Sánchez",
    tenant: "Laura Díaz",
    debt: 0,
    monthsOverdue: 0,
    waterReading: 145,
    electricityReading: 400,
  },
  {
    id: 6,
    number: "302",
    building: "edificio-1",
    owner: "Elena Castro",
    tenant: "Elena Castro",
    debt: 750.0,
    monthsOverdue: 3,
    waterReading: 130,
    electricityReading: 365,
  },
  {
    id: 7,
    number: "101",
    building: "edificio-2",
    owner: "Pedro Vargas",
    tenant: "Pedro Vargas",
    debt: 0,
    monthsOverdue: 0,
    waterReading: 88,
    electricityReading: 270,
  },
  {
    id: 8,
    number: "102",
    building: "edificio-2",
    owner: "Carmen Luna",
    tenant: "Diego Ramos",
    debt: 550.0,
    monthsOverdue: 2,
    waterReading: 140,
    electricityReading: 390,
  },
  {
    id: 9,
    number: "201",
    building: "edificio-2",
    owner: "Roberto Jiménez",
    tenant: "Roberto Jiménez",
    debt: 0,
    monthsOverdue: 0,
    waterReading: 105,
    electricityReading: 310,
  },
  {
    id: 10,
    number: "202",
    building: "edificio-2",
    owner: "Sofía Herrera",
    tenant: "Sofía Herrera",
    debt: 200.0,
    monthsOverdue: 1,
    waterReading: 95,
    electricityReading: 285,
  },
]

export const paymentHistory = [
  { id: 1, departmentId: 1, date: "2024-10-15", amount: 300.0, concept: "Mantenimiento Octubre" },
  { id: 2, departmentId: 1, date: "2024-09-18", amount: 280.0, concept: "Agua Septiembre" },
  { id: 3, departmentId: 3, date: "2024-08-20", amount: 350.0, concept: "Mantenimiento Agosto" },
  { id: 4, departmentId: 6, date: "2024-09-25", amount: 250.0, concept: "Agua Septiembre" },
]

export const recentActivity = [
  { id: 1, type: "payment", message: "Pago recibido - Dpto 102 - S/ 300.00", time: "Hace 2 horas" },
  { id: 2, type: "reading", message: "Lectura de agua registrada - Dpto 201", time: "Hace 4 horas" },
  { id: 3, type: "debt", message: "Nueva deuda generada - Dpto 301", time: "Hace 1 día" },
  { id: 4, type: "receipt", message: "Recibo emitido - Dpto 102", time: "Hace 1 día" },
  { id: 5, type: "payment", message: "Pago recibido - Dpto 302 - S/ 450.00", time: "Hace 2 días" },
]

export const monthlyData = [
  { month: "Jul", ingresos: 8500, gastos: 6200 },
  { month: "Ago", ingresos: 9200, gastos: 5800 },
  { month: "Sep", ingresos: 7800, gastos: 6500 },
  { month: "Oct", ingresos: 10500, gastos: 7200 },
  { month: "Nov", ingresos: 9800, gastos: 6800 },
  { month: "Dic", ingresos: 11200, gastos: 7500 },
]

export const defaultRates = {
  waterRate: 2.5,
  electricityRate: 0.85,
  maintenance: 150.0,
  cleaning: 50.0,
  security: 80.0,
  commonAreas: 40.0,
}
